numerador = int(input("Informe o número que deseja saber a tabuada: "))
print("-" * 20)
print(" {} x 1 = {}".format(numerador,(numerador *1)))
print(" {} x 2 = {}".format(numerador,(numerador *2)))
print(" {} x 3 = {}".format(numerador,(numerador *3)))
print(" {} x 4 = {}".format(numerador,(numerador *4)))
print(" {} x 5 = {}".format(numerador,(numerador *5)))
print(" {} x 6 = {}".format(numerador,(numerador *6)))
print(" {} x 7 = {}".format(numerador,(numerador *7)))
print(" {} x 8 = {}".format(numerador,(numerador *8)))
print(" {} x 9 = {}".format(numerador,(numerador *9)))
print(" {} x 10 = {}".format(numerador,(numerador *10)))
print("-" * 20)